dist: xenial
language: bash
git:
  depth: 1
  quiet: true

branches:
  # Don't build these branches
  except:
    # Used by bors
    - trying.tmp
    - staging.tmp

cache:
  directories:
    - $HOME/.cargo
before_cache:
  - cargo install cargo-cache --debug
  - find $HOME/.cargo/bin/ ! -type d -exec strip {} \;
  - cargo cache --autoclean

env:
  global:
    - RUST_BACKTRACE=1
    - secure: "OKulfkA5OGd/d1IhvBKzRkHQwMcWjzrzbimo7+5NhkUkWxndAzl+719TB3wWvIh1i2wXXrEXsyZkXM5FtRrHm55v1VKQ5ibjEvFg1w3NIg81iDyoLq186fLqywvxGkOAFPrsePPsBj5USd5xvhwwbrjO6L7/RK6Z8shBwOSc41s="

before_install:
  - export CARGO_TARGET_DIR="$TRAVIS_BUILD_DIR/target"
  - |
    case "$TRAVIS_OS_NAME" in
      linux ) HOST=x86_64-unknown-linux-gnu;;
      osx ) HOST=x86_64-apple-darwin;;
      windows ) HOST=x86_64-pc-windows-msvc;;
    esac
  - curl -sSL https://sh.rustup.rs | sh -s -- -y --default-host="$HOST" --default-toolchain=nightly --profile=minimal
  - export PATH="$HOME/.cargo/bin:$PATH"
install:
  - |
    if [[ -z ${INTEGRATION} ]]; then
      if ! rustup component add rustfmt; then
        TARGET=$(rustc -Vv | awk '/host/{print $2}')
        NIGHTLY=$(curl -s "https://rust-lang.github.io/rustup-components-history/${TARGET}/rustfmt")
        curl -sSL "https://static.rust-lang.org/dist/${NIGHTLY}/rustfmt-nightly-${TARGET}.tar.xz" | \
        tar -xJf - --strip-components=3 -C ~/.cargo/bin
        rm -rf ~/.cargo/bin/doc
      fi
      if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        . $HOME/.nvm/nvm.sh
        nvm install stable
        nvm use stable
        npm install remark-cli remark-lint
      elif [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
        choco install windows-sdk-10.1
      fi
    fi

# disabling the integration tests in forks should be done with
# if: fork = false
# but this is currently buggy travis-ci/travis-ci#9118
matrix:
  fast_finish: true
  include:
    # Builds that are executed for every PR
    - os: linux

before_script:
  - |
    SYSROOT=$(rustc --print sysroot)
    case "$TRAVIS_OS_NAME" in
      windows ) export PATH="${SYSROOT}/bin:${PATH}" ;;
      linux ) export LD_LIBRARY_PATH="${SYSROOT}/lib${LD_LIBRARY_PATH+:${LD_LIBRARY_PATH}}" ;;
      osx )
        # See <https://github.com/nteract/nteract/issues/1523#issuecomment-301623519>
        sudo mkdir -p /usr/local/lib
        sudo find "$SYSROOT/lib" -maxdepth 1 -name '*.dylib' -exec ln -s {} /usr/local/lib \;
        ;;
    esac

script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      set -e
      if [[ -z ${INTEGRATION} ]]; then
        ./.github/deploy.sh || sleep 5
      else
        echo "Not deploying, because we're in an integration test run"
      fi
      set +e
    fi
